// src/modules/dashboard/Dashboard.vue
<script setup lang="ts">
import { SidebarProvider } from '@/components/ui/sidebar';

import MainContent from './MainContent.vue';
import PrimarySidebar from './PrimarySidebar.vue';
</script>

<template>
    <SidebarProvider class="flex flex-col" :style="{ '--sidebar-width': '300px' }">
        <main class="flex flex-1">
            <PrimarySidebar />
            <MainContent />
        </main>
    </SidebarProvider>
</template>

// src/app/old-dashboard/Dashboard.tsx
import { Outlet } from 'react-router';

import { SidebarProvider } from '@/components/ui/sidebar';

import AppSidebar from './AppSidebar';

export default function Dashboard() {
    return (
        <SidebarProvider className='flex w-full'>
            <AppSidebar />
            <main className='flex flex-1 items-center justify-center'>
                <Outlet />
            </main>
        </SidebarProvider>
    );
}
