// src/app/dashboard/Dashboard.tsx
import { CSSProperties } from 'react';

import { SidebarProvider } from '@/components/ui/sidebar';
import { TabProvider } from '@/components/ui/tab-provider';

import MainContent from './MainContent';
import PrimarySidebar from './PrimarySidebar';

export default function Dashboard() {
    return (
        <SidebarProvider className='flex flex-col' style={{ '--sidebar-width': '300px' } as CSSProperties}>
            <TabProvider>
                <main className='flex flex-1'>
                    <PrimarySidebar />
                    <MainContent />
                </main>
            </TabProvider>
        </SidebarProvider>
    );
}

// src/modules/dashboard/Dashboard.vue
<script setup lang="ts">
import { SidebarProvider } from '@/components/ui/sidebar';

import MainContent from './MainContent.vue';
import PrimarySidebar from './PrimarySidebar.vue';
</script>

<template>
    <SidebarProvider class="flex flex-col" :style="{ '--sidebar-width': '300px' }">
        <main class="flex flex-1">
            <PrimarySidebar />
            <MainContent />
        </main>
    </SidebarProvider>
</template>
