// src/app/dashboard/MainContent.tsx
import { SidebarInset } from '@/components/ui/sidebar';
import { useTab } from '@/components/ui/tab-provider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

export default function MainContent() {
    const { tabs, activeTab } = useTab();

    return (
        <SidebarInset className='items-center justify-center'>
            <Tabs value={activeTab?.id} className='size-full'>
                <TabsList>
                    {tabs.map((tab) => (
                        <TabsTrigger key={tab.id} value={tab.id}>
                            {tab.name}
                        </TabsTrigger>
                    ))}
                </TabsList>

                {tabs.map((tab) => (
                    <TabsContent key={tab.id} value={tab.id} className='items-center justify-center'>
                        {tab.name}
                    </TabsContent>
                ))}
            </Tabs>
        </SidebarInset>
    );
}

// src/modules/dashboard/MainContent.vue
<script setup lang="ts">
import { useTabs } from '@/components/custom/tabs';
import { SidebarInset } from '@/components/ui/sidebar';
import { Tabs, TabsContent } from '@/components/ui/tabs';
import { Todo } from '@/modules/todo';

import TabsList from './TabsList.vue';

const { tabs, currentTab, activeTab } = useTabs();
</script>

<template>
    <SidebarInset class="min-w-0 items-center justify-center">
        <Tabs
            class="size-full gap-0"
            :model-value="currentTab"
            @update:model-value="(value) => activeTab(value as string)"
        >
            <TabsList />

            <TabsContent v-for="tab in tabs" :key="tab.id" as-child :value="tab.id">
                <component :is="tab.component" v-if="tab.component" />
                <Todo v-else />
            </TabsContent>
        </Tabs>
    </SidebarInset>
</template>
