// src/tiptap/ui/MarkButton.tsx
import { Bold, Code, Italic, Strikethrough, Subscript, Superscript, Underline } from 'lucide-react';
import { ComponentProps } from 'react';

import { Toggle } from '@/components/ui/toggle';
import { useTiptapEditor } from '@/tiptap/hooks';

const MARK_ICONS = {
    bold: Bold,
    italic: Italic,
    underline: Underline,
    strike: Strikethrough,
    superscript: Superscript,
    subscript: Subscript,
    code: Code,
} as const;

type MarkButtonProps = {
    mark: keyof typeof MARK_ICONS;
};

export default function MarkButton({ mark, ...props }: MarkButtonProps & ComponentProps<'button'>) {
    const { editor, editorState } = useTiptapEditor({
        selector({ editor }) {
            return {
                isActive: editor?.isActive(mark),
                canActive: editor?.can().toggleMark(mark),
            };
        },
    });

    const Icon = MARK_ICONS[mark];
    return (
        <Toggle
            data-state={editorState?.isActive ? 'on' : 'off'}
            size='sm'
            onClick={() => editor?.chain().focus().toggleMark(mark).run()}
            disabled={!editorState?.canActive}
            {...props}
        >
            <Icon />
        </Toggle>
    );
}

// src/components/tiptap/mark/MarkButton.vue
<script setup lang="ts">
import { Editor } from '@tiptap/vue-3';
import { Bold, Code2, Italic, Strikethrough, Subscript, Superscript, Underline } from 'lucide-vue-next';

import { Button, ButtonProps } from '@/components/ui/button';
import { cn } from '@/lib/utils';

type MarkType = 'bold' | 'italic' | 'strike' | 'underline' | 'code' | 'superscript' | 'subscript';

const MARK_ICONS = {
    bold: Bold,
    italic: Italic,
    strike: Strikethrough,
    underline: Underline,
    code: Code2,
    superscript: Superscript,
    subscript: Subscript,
};

interface Props extends ButtonProps {
    editor: Editor;
    type: MarkType;
}

const props = withDefaults(defineProps<Props>(), {
    variant: 'ghost',
    size: 'icon-sm',
});

const emits = defineEmits<{
    (e: 'update:toggle', type: MarkType): void;
}>();
</script>

<template>
    <Button
        :class="cn('data-[active-state=true]:bg-accent rounded!', props.class)"
        :data-active-state="editor.isActive(props.type)"
        :disabled="!editor.isEditable || !editor.can().toggleMark(props.type)"
        :size="size"
        :variant="variant"
        @click="
            () => {
                editor.chain().focus().toggleMark(props.type).run();
                emits('update:toggle', props.type);
            }
        "
    >
        <component :is="MARK_ICONS[props.type]" />
    </Button>
</template>
