// src/components/tiptap/heading/HeadingDropdown.vue
<script setup lang="ts">
import { Editor } from '@tiptap/vue-3';
import { ChevronDown, Heading, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6 } from 'lucide-vue-next';

import { Button } from '@/components/ui/button';
import { ButtonGroup } from '@/components/ui/button-group';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

type HEADING_LEVELS = 0 | 1 | 2 | 3 | 4 | 5 | 6;

const HEADING_ICONS = [Heading, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6];

const props = withDefaults(
    defineProps<{
        editor: Editor;
        levels?: HEADING_LEVELS[];
    }>(),
    { levels: () => [1, 2, 3, 4, 0] }
);
</script>

<template>
    <DropdownMenu>
        <DropdownMenuTrigger as-child>
            <Button class="gap-1 px-2!" size="sm" variant="outline">
                <component :is="HEADING_ICONS[props.editor.getAttributes('heading').level ?? 0]" />
                <ChevronDown class="size-3" />
            </Button>
        </DropdownMenuTrigger>

        <DropdownMenuContent align="start" as-child>
            <ButtonGroup class="min-w-0 p-0.5 text-xs" orientation="vertical">
                <DropdownMenuItem v-for="level in props.levels" :key="level" as-child>
                    <Button
                        class="data-[active-state=true]:bg-accent justify-start rounded! px-2! py-1 text-xs"
                        :data-active-state="
                            level === 0 ? editor.isActive('paragraph') : editor.isActive('heading', { level })
                        "
                        size="sm"
                        variant="ghost"
                        @click="
                            level === 0
                                ? editor.chain().focus().setParagraph().run()
                                : editor.chain().focus().toggleHeading({ level }).run()
                        "
                    >
                        <component :is="HEADING_ICONS[level]" />
                        <div v-if="level === 0" class="flex-1">Paragraph</div>
                        <div v-else class="flex-1">Heading {{ level }}</div>
                    </Button>
                </DropdownMenuItem>
            </ButtonGroup>
        </DropdownMenuContent>
    </DropdownMenu>
</template>

// src/tiptap/ui/HeadingDropdown.tsx
import { ChevronDown, Heading, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6 } from 'lucide-react';
import { ComponentProps, useRef } from 'react';

import { cn } from '@/libs';
import { useTiptapEditor } from '@/tiptap/hooks';

const HEADING_ICONS = [Heading1, Heading2, Heading3, Heading4, Heading5, Heading6] as const;

export default function HeadingDropdown({ className, ...props }: ComponentProps<'div'>) {
    const ref = useRef<HTMLDivElement>(null);

    const { editor, editorState } = useTiptapEditor({
        selector({ editor }) {
            const level: number = editor?.getAttributes('heading').level ?? 0;
            return { level };
        },
    });
    const isHeading = editorState?.level !== 0;

    return (
        <div ref={ref} className={cn('dropdown', className)} {...props}>
            <div
                tabIndex={0}
                role='button'
                className={cn('btn btn-ghost m-0 size-fit gap-0 border-none p-1', isHeading && 'btn-active')}
            >
                {isHeading ? (
                    (() => {
                        const Icon = HEADING_ICONS[editorState!.level - 1];
                        return <Icon size={20} strokeWidth={1.5} />;
                    })()
                ) : (
                    <Heading size={20} strokeWidth={1.5} />
                )}
                <ChevronDown size={12} strokeWidth={1.5} />
            </div>

            <ul tabIndex={0} className='dropdown-content menu bg-base-100 rounded-box z-1 p-2 shadow-sm'>
                {HEADING_ICONS.map((Icon, i) => (
                    <li key={`heading-${i + 1}`}>
                        <button
                            className='grid-cols-1'
                            onClick={() => {
                                editor
                                    ?.chain()
                                    .focus()
                                    .setNode('heading', { level: i + 1 })
                                    .run();
                                ref.current?.blur();
                            }}
                        >
                            <Icon size={20} strokeWidth={1.5} />
                            Heading {i + 1}
                        </button>
                    </li>
                ))}
                <hr className='bg-neutral my-1 h-px border-0' />
                <li key='paragraph'>
                    <button
                        onClick={() => {
                            editor?.chain().focus().setNode('paragraph').run();
                            ref.current?.blur();
                        }}
                    >
                        <div className='size-5'></div>
                        Paragraph
                    </button>
                </li>
            </ul>
        </div>
    );
}
