// src/tiptap/ui/TextAlignDropdown.tsx
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, ChevronDown } from 'lucide-react';
import { ComponentProps, useRef } from 'react';

import { cn } from '@/libs';
import { useTiptapEditor } from '@/tiptap/hooks';

const TEXT_ALIGN_ICONS = {
    left: AlignLeft,
    center: AlignCenter,
    right: AlignRight,
    justify: AlignJustify,
} as const;

export default function TextAlignDropdown({ className, ...props }: ComponentProps<'div'>) {
    const ref = useRef<HTMLDivElement>(null);

    const { editor, editorState } = useTiptapEditor({
        selector({ editor }) {
            const align: keyof typeof TEXT_ALIGN_ICONS =
                editor?.getAttributes('paragraph').textAlign ?? editor?.getAttributes('heading').textAlign ?? 'left';
            return { align };
        },
    });

    return (
        <div ref={ref} className={cn('dropdown', className)} {...props}>
            <div tabIndex={0} role='button' className='btn btn-ghost m-0 size-fit gap-0 border-none p-1'>
                {(() => {
                    const Icon = TEXT_ALIGN_ICONS[editorState!.align];
                    return <Icon size={20} strokeWidth={1.5} />;
                })()}
                <ChevronDown size={12} strokeWidth={1.5} />
            </div>

            <ul tabIndex={0} className='dropdown-content menu bg-base-100 rounded-box z-1 p-2 shadow-sm'>
                <div className='menu-horizontal'>
                    {Object.entries(TEXT_ALIGN_ICONS).map(([align, Icon]) => (
                        <li key={align}>
                            <button
                                className='m-0 size-fit p-1'
                                onClick={() => {
                                    editor?.chain().focus().setTextAlign(align).run();
                                    ref.current?.blur();
                                }}
                            >
                                <Icon size={20} strokeWidth={1.5} />
                            </button>
                        </li>
                    ))}
                </div>
            </ul>
        </div>
    );
}

// src/components/tiptap/text-align/TextAlignDropdown.vue
<script setup lang="ts">
import type { Editor } from '@tiptap/vue-3';
import { ChevronDown } from 'lucide-vue-next';
import { computed } from 'vue';

import { Button } from '@/components/ui/button';
import { ButtonGroup } from '@/components/ui/button-group';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

import TextAlignButton from './TextAlignButton.vue';
import type { TextAlign } from './types';
import { ALIGN_ICONS } from './types';

const props = withDefaults(
    defineProps<{
        editor: Editor;
        aligns?: TextAlign[];
        orientation?: 'horizontal' | 'vertical';
    }>(),
    {
        aligns: () => ['left', 'center', 'right', 'justify'],
        orientation: 'horizontal',
    }
);

const currentAlign = computed<TextAlign>(
    () => props.editor.getAttributes('paragraph').textAlign ?? props.editor.getAttributes('heading').textAlign ?? 'left'
);
</script>

<template>
    <DropdownMenu>
        <DropdownMenuTrigger as-child>
            <Button class="gap-0 rounded! px-1!" size="sm" variant="ghost">
                <component :is="ALIGN_ICONS[currentAlign]" />
                <ChevronDown class="size-2" />
            </Button>
        </DropdownMenuTrigger>

        <DropdownMenuContent align="start" as-child>
            <ButtonGroup class="gap-0.5 p-0.5" :orientation="orientation">
                <DropdownMenuItem v-for="align in aligns" :key="align" as-child>
                    <TextAlignButton :align="align" :editor="editor" />
                </DropdownMenuItem>
            </ButtonGroup>
        </DropdownMenuContent>
    </DropdownMenu>
</template>
