// src/App.tsx
import { useEffect } from 'react';

import { Dashboard } from '@/modules/dashboard';
import { loadSystemFonts } from '@/utils';

export default function App() {
    useEffect(() => {
        const controller = new AbortController();
        loadSystemFonts();
        return () => controller.abort();
    }, []);

    return (
        <div
            className='h-screen overflow-hidden'
            onContextMenu={(e) => {
                if (import.meta.env.PROD) {
                    e.preventDefault();
                    e.stopPropagation();
                }
            }}
        >
            <Dashboard />
        </div>
    );
}

// src/App.vue
<script setup lang="ts">
import { Dashboard } from '@/modules/dashboard';

const IS_PROD = import.meta.env.PROD;
</script>

<template>
    <div
        class="h-screen overflow-hidden"
        @contextmenu="
            (ev) => {
                if (IS_PROD) {
                    ev.preventDefault();
                    ev.stopPropagation();
                }
            }
        "
    >
        <Dashboard />
    </div>
</template>
